post http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Seuraava blogi",
    "author": "Hyvä kirjoittaja myös",
    "url": "www.54321.fi",
    "likes": 0,
    "userId": "5ed8e7e864bed53290c243bd"
}